---
- name: Config Routers
  hosts: arista
  gather_facts: false
  pre_tasks:
    - include_vars: "../../config_vars/{{inventory_hostname}}.yml"

  tasks:
  #--------------------ARISTA--------------------------#
    - name: Configure Arista Routers using template 
      ansible.netcommon.cli_config:
        config: "{{ lookup('template', '../../templates/{{ansible_network_os}}.j2') }}"
      when: ansible_network_os == 'arista.eos.eos'